services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: bun dev
    environment:
      - NODE_ENV=development
      - INNGEST_DEV=1
      - INNGEST_BASE_URL=http://inngest:8288
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
  inngest:
    image: inngest/inngest:v1.15.3
    command: "inngest dev -u http://app:3000/api/inngest"
    ports:
      - "8288:8288"
